version: '3.8'

services:
  # Project1 - Image conversion microservice
  project1:
    build:
      context: ./project1
      dockerfile: Dockerfile
    container_name: project1
    ports:
      - "5000:5000"
    volumes:
      - project1_uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - SECRET_KEY=your-secret-key-here
    networks:
      - project-network

volumes:
  project1_uploads:

networks:
  project-network:
    driver: bridge 